name: myassigment
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  google_sign_in: ^5.2.4
  image_picker: ^0.8.4+10
  flutter_image_compress: ^1.1.0
  pull_to_refresh: ^2.0.0
  # flutter_native_image: ^0.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/img/
